# Development docker-compose configuration
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Add your environment variables here
      # - GROQ_API_KEY=${GROQ_API_KEY}
      # - NEON_DATABASE_URL=${NEON_DATABASE_URL}
    volumes:
      # Mount logs directory for debugging
      - ./logs:/app/logs
    networks:
      - career-coach-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Local PostgreSQL for development
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: career_coach
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - career-coach-network

networks:
  career-coach-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local